services:
  # analyse the existing db and add new urls to crawl to the queue 
  # provide a montinoring and managment interface for the system
  dispatcher:
    build: ./dispatcher
    depends_on:
      - db
      - queue

  # does the actual crawling and scraping
  crawler:
    build: ./crawler
    depends_on:
      - dispatcher
      - queue
  
  # message queue to coordinate and synchonize the crawlers on a set of urls
  queue:
    image: redis:latest
    volumes:
      - queue-data:/var/lib/redis/data

  # database to save the scraped data and metadata
  db:
    image: postgres:latest
    restart: always
    environment:
      # set values in the .env file
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # admin interface into the postgress database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# persistent storage
volumes:
  db-data:
  queue-data:

